# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - 'release/**'
jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Set major release
      if: ${{ github.event.label.name == 'release-major' }}
      run: echo "major" >> $GITHUB_ENV
    - name: Set minor release
      if: ${{ github.event.label.name == 'release-minor' }}
      run: echo "minor" >> $GITHUB_ENV
    - name: Set patch release
      if: ${{ github.event.label.name == 'release-patch' }}
      run: echo "patch" >> $GITHUB_ENV
    - name: Tagging
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: $GITHUB_ENV
        use_github_release_notes: true
